### ISSUE TITLE
Mute error

### ISSUE THREAD

**Issue by RepublicofTexas** [Votyn/SpaceBoat#8]
```bash
(node:3844) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'position' of null
    at Function.comparePositions (C:\Users\user\SpaceBoat\node_modules\discord.js\src\structures\Role.js:356:34)
    at Role.comparePositionTo (C:\Users\user\SpaceBoat\node_modules\discord.js\src\structures\Role.js:188:29)
    at Object.module.exports.run (C:\Users\user\SpaceBoat\cmds\mute.js:26:38)
    at Client.bot.on.message (C:\Users\user\SpaceBoat\bot.js:240:18)
    at Client.emit (events.js:180:13)
    at MessageCreateHandler.handle (C:\Users\user\SpaceBoat\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\user\SpaceBoat\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\user\SpaceBoat\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\Users\user\SpaceBoat\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)
    at WebSocket.onMessage (C:\Users\user\SpaceBoat\node_modules\ws\lib\event-target.js:120:16)
(node:3844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

With the following: =mute @Gunnery Sergeant Hartman 1
(Tagged but of course won't show up on here) Any fix?
EDIT: Welp sorry for tagging you Gunnery didn't mean to, sorry.

**Comment by Votyn** [comment]
Reason: role was not defined. The role compare position check did not work as it depends on role, but is above the role creator. 
Fixed in [latest commit](https://github.com/Votyn/SpaceBoat/commit/e6426dc51eb17c0e5c872e08c20f81130c8989d6).
